# steps:
#   # Build the Docker image
#   - id: build
#     name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/dreamdev-team1/landing-page:$COMMIT_SHA', '.']
#     dir: 'src/landing-page'

#   # Push the image to Google Container Registry (GCR)
#   - id: push
#     name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/dreamdev-team1/landing-page:$COMMIT_SHA']
#     waitFor: ['build']

#   # Deploy to Cloud Run 
#   - id: deploy
#     name: 'gcr.io/cloud-builders/gcloud'
#     args: ['run', 'deploy', 'landing-page',
#            '--image=gcr.io/dreamdev-team1/landing-page:$COMMIT_SHA',
#            '--platform=managed',
#            '--region=europe-west1',  # Updated region
#            '--allow-unauthenticated',
#            '--port=80'
#           ]
#     waitFor: ['push']

# options:
#   logging: CLOUD_LOGGING_ONLY

# substitutions:
#   _TAG: $COMMIT_SHA
#   _PROJECT_ID: dreamdev-team1
#   _APP_NAME: landing-page
#   _REGION: europe-west1  # Updated region
#   _DIR: src/landing-page

steps:
  # Build the Docker image
  - id: build
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/dreamdev-team1/landing-page-repo/landing-page:$COMMIT_SHA', '.']
    dir: 'src/landing-page'

  # Push the image to Artifact Registry
  - id: push
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/dreamdev-team1/landing-page-repo/landing-page:$COMMIT_SHA']
    waitFor: ['build']

  # Deploy to Cloud Run 
  - id: deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'landing-page',
           '--image=europe-west1-docker.pkg.dev/dreamdev-team1/landing-page-repo/landing-page:$COMMIT_SHA',
           '--platform=managed',
           '--region=europe-west1',
           '--allow-unauthenticated',
           '--port=80'
          ]
    waitFor: ['push']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _TAG: $COMMIT_SHA
  _PROJECT_ID: dreamdev-team1
  _APP_NAME: landing-page
  _REGION: europe-west1
  _DIR: src/landing-page